# Generated by Django 2.2.7 on 2019-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField()),
                ('adminId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField()),
                ('bannedUser', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField()),
                ('chatName', models.CharField(max_length=45)),
                ('user1Id', models.IntegerField()),
                ('user2Id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField()),
                ('chatName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockingId', models.IntegerField()),
                ('blockedId', models.IntegerField()),
            ],
        ),
    ]
